- alias: "Set fan speed"
  trigger:
    platform: numeric_state
    entity_id: sensor.cpu_temp
    above: 50.0
    for:
      minutes: 1
  action:
    - service: argon40.set_fan_speed
      data:
        speed: 40
- alias: "Argon40 button double-tap"
  trigger:
    platform: event
    event_type: argon40_event
    event_data:
      action: double-tap
  action:
    - service: persistent_notification.create
      data:
        title: "Argon 40"
        message: "Button was double-tapped"
